// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arapoint-hero/BoldNigerian.tsx": () => import("../components/mockups/arapoint-hero/BoldNigerian.tsx"),
  "./components/mockups/arapoint-hero/DarkInfrastructure.tsx": () => import("../components/mockups/arapoint-hero/DarkInfrastructure.tsx"),
  "./components/mockups/arapoint-hero/EditorialMinimal.tsx": () => import("../components/mockups/arapoint-hero/EditorialMinimal.tsx"),
  "./components/mockups/arapoint-video/VideoAd.tsx": () => import("../components/mockups/arapoint-video/VideoAd.tsx"),
  "./components/mockups/arapoint-video/VideoTemplate.tsx": () => import("../components/mockups/arapoint-video/VideoTemplate.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene1.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene1.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene2.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene2.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene3.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene3.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene4.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene4.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene5.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene5.tsx"),
  "./components/mockups/arapoint-video/video_scenes/Scene6.tsx": () => import("../components/mockups/arapoint-video/video_scenes/Scene6.tsx")
};
